<a href="https://colab.research.google.com/github/kurek0010/neutral-network/blob/main/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
def max_relu(x):
    return max(x, 0.0)

In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [4]:
data = np.random.randn(50)
data = sorted(data)
data

[-1.8575888559271492,
 -1.7629580351836838,
 -1.7499616221336398,
 -1.6196381709099947,
 -1.482254650897959,
 -1.4028401441582692,
 -1.2639880732884934,
 -1.240750502303196,
 -1.1504411823433878,
 -0.8986665142466629,
 -0.8415521474288535,
 -0.809502433832212,
 -0.7595697961566452,
 -0.6848510985105585,
 -0.6081983945766111,
 -0.5620599765012121,
 -0.5501101328886652,
 -0.5476924741173607,
 -0.4870633209026812,
 -0.35590807937423624,
 -0.34767274905991424,
 -0.3395965264156013,
 -0.2904955745793874,
 -0.18093976502640957,
 -0.11693771735894189,
 -0.04253700297339736,
 -0.00940591667976852,
 -0.003531800386861027,
 0.0003866815688482309,
 0.19501615575153658,
 0.19972664507370672,
 0.38401932972217817,
 0.44116371730759896,
 0.5287690496766917,
 0.6689427211290105,
 0.6720567803249651,
 0.7239839267398128,
 0.8300614323935281,
 0.8758814440703101,
 0.962772926830572,
 1.1033323390987642,
 1.1153461936759668,
 1.3183932922752055,
 1.4716134797828062,
 1.4842731075372206,
 1.4963827594968

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       3.866816e-04, 1.950162e-01, 1.997266e-01, 3.840193e-01,
       4.411637e-01, 5.287690e-01, 6.689427e-01, 6.720568e-01,
       7.239839e-01, 8.300614e-01, 8.758814e-01, 9.627729e-01,
       1.103332e+00, 1.115346e+00, 1.318393e+00, 1.471613e+00,
       1.484273e+00, 1.496383e+00, 1.657413e+00, 1.660120e+00,
       1.777319e+00, 1.809174e+00])

In [6]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -1.857589            0.0
1 -1.762958            0.0
2 -1.749962            0.0
3 -1.619638            0.0
4 -1.482255            0.0

In [7]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [9]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [10]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.357261275378022,
 -5.036359426343749,
 -4.991583845290266,
 -4.871814186785772,
 -4.615946617803589,
 -4.611073873501834,
 -4.567252274617858,
 -4.249103584997897,
 -4.034050367472541,
 -3.7487492245916556,
 -3.365598838286269,
 -3.338121785921915,
 -3.1664422177332603,
 -3.0127947195148437,
 -2.2527740553572158,
 -2.1206561119086382,
 -1.9902467479094184,
 -1.969134421454643,
 -1.8915334230766299,
 -1.8635831811476868,
 -1.8074956617823343,
 -1.6770613032926973,
 -0.9508040891896752,
 -0.8631193185237915,
 -0.7238837215241747,
 -0.6786339354595001,
 -0.6283253638356046,
 -0.6242981885657903,
 -0.375255558993535,
 -0.08300014984485829,
 0.1826100827130497,
 0.28732307311884453,
 0.5066966482727184,
 0.6002873549250556,
 0.6594380824100138,
 0.9822573031466186,
 1.0845923005893856,
 1.3501297189097574,
 1.4401693952423205,
 1.7421465264580382,
 1.8797126817454424,
 2.1605345065320614,
 2.4488964051276256,
 2.6674574827565416,
 3.2362976749276346,
 3.4455330766631693,
 3.445862767126

In [11]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0017311075326777994,
 0.00645541626902726,
 0.006749034928009193,
 0.007601235652377953,
 0.009795905188531174,
 0.009843283618583942,
 0.01027969009679595,
 0.01407606200737278,
 0.017394556152931413,
 0.023005465840185896,
 0.033388057501554796,
 0.03428629238706563,
 0.04044827527917361,
 0.04685118608710369,
 0.09511044904029795,
 0.10710530786026198,
 0.12023076018172396,
 0.12248188887445698,
 0.1310697283657602,
 0.13428594942533126,
 0.14094107013590704,
 0.1574849930068666,
 0.2787231419004569,
 0.296688042876247,
 0.3265383349687162,
 0.33656626221247365,
 0.34789035337580265,
 0.3488045278136255,
 0.40727170626921405,
 0.4792618666317777,
 0.5455260798677304,
 0.5713406509710037,
 0.6240317730211437,
 0.6457220457520818,
 0.6591341501654434,
 0.7275558849373793,
 0.747362049435877,
 0.7941508348441222,
 0.8084808818914793,
 0.8509595090273568,
 0.8675781210055709,
 0.8966490914963673,
 0.9204807095910743,
 0.9350788549822907,
 0.9621776052994238,
 0.9690976478631873,
 0.9

In [12]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.357261      0.001731
1 -5.036359      0.006455
2 -4.991584      0.006749
3 -4.871814      0.007601
4 -4.615947      0.009796

In [13]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [14]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [15]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.2157682572650454,
 -3.5014968011366947,
 -3.407012387549064,
 -3.3890667868515183,
 -3.3153168432548044,
 -3.1067975984394,
 -2.9010400998915227,
 -2.7307320870814866,
 -2.7080137257709898,
 -2.6839820166663615,
 -2.6260839404129723,
 -2.539271353108927,
 -2.4089066513848048,
 -2.356580677635551,
 -2.126898006436856,
 -1.9061377083692062,
 -1.801497755283259,
 -1.7989061376127133,
 -1.7333552196936708,
 -1.605976254788055,
 -1.605775806980571,
 -1.5937829560071173,
 -1.590968480323874,
 -1.5694331810489184,
 -1.485302822455627,
 -1.4648598744780028,
 -1.0672984564179755,
 -1.017030963126331,
 -0.9830567192040761,
 -0.9713341728595889,
 -0.9456744071669881,
 -0.9096953206418411,
 -0.8474599576850788,
 -0.8352780696434151,
 -0.7965784274124593,
 -0.7667270793964828,
 -0.7210371845979464,
 -0.7043441986794402,
 -0.6700081609050865,
 -0.6252260385908023,
 -0.5664732895528308,
 -0.49317106723668114,
 -0.4451567582922366,
 -0.4276922074016162,
 -0.4134340562031911,
 -0.21931339963299154,

In [16]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9995643220335947,
 -0.9981833391574513,
 -0.9978058822634813,
 -0.9977257936471003,
 -0.997364823096487,
 -0.9960039465474181,
 -0.9939756743293409,
 -0.9915412623589351,
 -0.9911497997301093,
 -0.9907160634824221,
 -0.9895822395523007,
 -0.9876191602841953,
 -0.9839607761192851,
 -0.982207005773596,
 -0.9719778217874022,
 -0.9567598344309779,
 -0.9469608981919078,
 -0.9466926168397828,
 -0.9394511862263839,
 -0.9225632040699264,
 -0.9225333564555388,
 -0.9207273398703818,
 -0.9202976922831118,
 -0.9169355541680783,
 -0.9024567646666761,
 -0.8985923749231878,
 -0.788441238861705,
 -0.768654463863571,
 -0.7543860903122912,
 -0.7492899930033821,
 -0.7378184900571749,
 -0.7209859855188703,
 -0.6897401628029057,
 -0.6832999097476744,
 -0.6621195739467273,
 -0.6450222737385701,
 -0.6175513477391521,
 -0.6071179740803476,
 -0.5849852510865245,
 -0.5547562161769555,
 -0.5127645396363756,
 -0.4567296405698315,
 -0.417909734291991,
 -0.4033908503176541,
 -0.3913846034237861,
 -0.21586355180

In [17]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.215768  -0.999564
1 -3.501497  -0.998183
2 -3.407012  -0.997806
3 -3.389067  -0.997726
4 -3.315317  -0.997365

In [18]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [19]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [20]:
data = np.random.randn(4, 5)
data

array([[ 1.85635 , -1.378294, -0.212541,  1.21489 ,  1.569482],
       [ 0.660807,  0.470685,  1.188859, -0.952756,  0.052433],
       [-0.976664,  1.16489 ,  0.976292, -0.714582, -0.055608],
       [ 1.667142,  1.350887, -1.407785, -1.228379,  2.248495]])

In [21]:
result = softmax(data)
result

array([[0.409361, 0.016118, 0.051713, 0.215538, 0.30727 ],
       [0.234417, 0.19383 , 0.397484, 0.04669 , 0.127578],
       [0.049083, 0.417825, 0.346009, 0.06379 , 0.123293],
       [0.276335, 0.201413, 0.012765, 0.015273, 0.494214]])

In [22]:
result.sum(axis=1)

array([1., 1., 1., 1.])