<a href="https://colab.research.google.com/github/kurek0010/neutral-network/blob/main/02_basics/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Spis treści:
1. [Funkcje aktywacji](#a0)
    1. [Import bibliotek](#a1)
    2. [ReLU Function - Rectified Linear Unit](#a2)
    3. [Funkcja Sigmoid](#a3)
    4. [Tanh Function](#a4)
    5. [Funkcja Softmax](#a5)
  

### <a name='a0'></a> 1. Funkcje Aktywacji
#### <a name='a1'></a> 1.1 Import bibliotek

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [ ]:
def max_relu(x):
    return max(x, 0.0)

In [ ]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0.0
0.0
0.0
5.0
10.0


In [ ]:
data = np.random.randn(50)
data = sorted(data)
data

[-1.5797220499662428,
 -1.358838889539144,
 -1.22166017145284,
 -1.1926521592885908,
 -1.1341014613159428,
 -1.1185265205545507,
 -0.9533366125664716,
 -0.8690937562126144,
 -0.8613103951105231,
 -0.7574854674492546,
 -0.6634324176984105,
 -0.40259762073340505,
 -0.35453938093851173,
 -0.32150344496790284,
 -0.29870787492254597,
 -0.22740174055235238,
 -0.21133188633733038,
 -0.20304842595348832,
 -0.18894717021645552,
 -0.1850975420744511,
 -0.1699276415344287,
 -0.15856484525817796,
 -0.1364540968664667,
 -0.1028839765582941,
 -0.04968576908410441,
 -0.02711845944252808,
 -0.019070191179337292,
 0.025514277444553576,
 0.03520856000665053,
 0.054660240794517666,
 0.15150587529697715,
 0.1684314365267077,
 0.18847180662057603,
 0.2582618907517759,
 0.2805593243189462,
 0.304930060059796,
 0.3260430529092424,
 0.49481197155544443,
 0.5930278900248482,
 0.6364597622107113,
 0.684246908243595,
 0.6871298341686636,
 0.7438407894256032,
 0.8763693049812281,
 1.1108432170145532,
 1.183329452

In [ ]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.025514, 0.035209, 0.05466 ,
       0.151506, 0.168431, 0.188472, 0.258262, 0.280559, 0.30493 ,
       0.326043, 0.494812, 0.593028, 0.63646 , 0.684247, 0.68713 ,
       0.743841, 0.876369, 1.110843, 1.183329, 1.465821, 1.489915,
       1.727783, 2.043058])

In [ ]:
df = pd.DataFrame({'data': data, 'max_relu_data': max_relu_data})
df.head()

data  max_relu_data
0 -1.579722            0.0
1 -1.358839            0.0
2 -1.221660            0.0
3 -1.192652            0.0
4 -1.134101            0.0

In [ ]:
px.line(df, x='data', y='max_relu_data', width=700, height=400, title='ReLU Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
for i in [-5., -3., -1., 0., 1., 3., 5.]:
    print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [ ]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-7.647391961111659,
 -6.65313531097829,
 -5.750612774187644,
 -4.787702477351778,
 -4.612361637430961,
 -4.592712003926982,
 -4.398910656973605,
 -3.8435194383113176,
 -3.442164497031639,
 -3.3586353622508893,
 -3.003329779477853,
 -2.945420383264633,
 -2.9205248492859104,
 -2.193386080548605,
 -1.6879897141323337,
 -1.6707143514325145,
 -1.5309736046444533,
 -1.411781698511211,
 -1.2655595579345427,
 -1.174912563637477,
 -1.1742599960568196,
 -0.813764906696854,
 -0.6871403654788645,
 -0.6212673972013364,
 -0.5271167503604521,
 -0.22701314210178913,
 -0.1901430800649474,
 -0.08836818267245866,
 -0.08121218927565359,
 0.5787070667976575,
 0.5802908412288956,
 0.6548680297003242,
 0.8372196660281892,
 0.8605756466718426,
 0.9820874715433526,
 0.9965705596170036,
 1.719443087682565,
 1.7480688726220737,
 1.8295688951396043,
 1.8508460371763307,
 2.089232605086383,
 2.0941452807665293,
 2.285441023471363,
 2.438291194857111,
 2.8907715383898642,
 3.415959991332347,
 4.031681911650685,
 4

In [ ]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.000477059596543607,
 0.0012883094151746957,
 0.003170745462349847,
 0.008262735774329328,
 0.009830740483779209,
 0.010023865823889136,
 0.012141493708037496,
 0.020968973559867782,
 0.031003391894338057,
 0.0336135235010082,
 0.04727567135184786,
 0.049953403887402936,
 0.05114822288689684,
 0.1003459955271467,
 0.15604039525105293,
 0.15832896049339967,
 0.17785128046444007,
 0.19595318782410812,
 0.22001833007028343,
 0.23596816349465574,
 0.23608583333978414,
 0.30708879769721453,
 0.3346695148106505,
 0.3494932566267554,
 0.37118961091877345,
 0.4434891964775577,
 0.45260693297289023,
 0.4779223193947626,
 0.4797081042527142,
 0.640769848191538,
 0.6411343261516946,
 0.6581066220471775,
 0.6978793226145711,
 0.7027809093996539,
 0.7275222199014837,
 0.7303837756727772,
 0.8480570886124996,
 0.8517090647843407,
 0.8617103619624781,
 0.8642264068469864,
 0.8898522317423493,
 0.890332827403604,
 0.9076640716889858,
 0.9197009811837066,
 0.9473883511413119,
 0.9681996183283971,
 0.

In [ ]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -7.647392      0.000477
1 -6.653135      0.001288
2 -5.750613      0.003171
3 -4.787702      0.008263
4 -4.612362      0.009831

In [ ]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [ ]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [ ]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.325856900294617,
 -4.296594202607075,
 -3.960083295229817,
 -3.510984321031611,
 -3.2712622380541325,
 -3.2631649653380785,
 -3.0461198961725726,
 -2.7448910657668755,
 -2.729189340273211,
 -2.5790472475250845,
 -2.484838330845703,
 -2.4230336823076413,
 -2.390652531330091,
 -2.3486929794932454,
 -2.3423709396188372,
 -2.287465638860627,
 -2.241920678190039,
 -2.2211741652214383,
 -1.9862900414449005,
 -1.9477798440807563,
 -1.8088738102917474,
 -1.736913214628526,
 -1.719721802473026,
 -1.591361509276441,
 -1.4012689400736136,
 -1.387303448379706,
 -1.2652863524165743,
 -1.2617358624172212,
 -1.253828059805766,
 -1.2319451646094897,
 -1.0584256292877259,
 -1.0372320340805483,
 -0.893142950046301,
 -0.8366145306283419,
 -0.7317411843065749,
 -0.7090768835449909,
 -0.7019290569766113,
 -0.677462143784749,
 -0.6419668805400927,
 -0.6123676032357502,
 -0.6007404450457675,
 -0.3386910441226449,
 -0.32551994951021795,
 -0.2712570640294516,
 -0.22929838476082615,
 -0.10095405383979958,
 

In [ ]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9996504071728578,
 -0.9996293404499845,
 -0.9992735803542623,
 -0.9982174549481209,
 -0.9971224530609107,
 -0.997075541809028,
 -0.995489514139215,
 -0.9917764656661262,
 -0.9915152335663289,
 -0.9885605055121526,
 -0.9862050247627936,
 -0.9844041228597427,
 -0.983369351182829,
 -0.981926645171903,
 -0.9816987777874945,
 -0.9795962862804131,
 -0.9776721584860113,
 -0.9767372221407031,
 -0.9630460490132688,
 -0.9601463212863595,
 -0.9477172899454553,
 -0.9398676131070755,
 -0.9378295243586942,
 -0.9203578244591699,
 -0.8856256247712578,
 -0.8825762080011137,
 -0.8525149625995747,
 -0.8515419629445514,
 -0.8493536051321905,
 -0.8431426163423277,
 -0.7850605507528774,
 -0.7767926683051722,
 -0.7129426261976906,
 -0.6840117282879449,
 -0.6241294325021595,
 -0.6100976443291536,
 -0.6055907985628582,
 -0.5898670459673219,
 -0.5662372911048109,
 -0.5457915682115005,
 -0.5375762416955792,
 -0.32630831278654854,
 -0.31448952652926193,
 -0.2647941478797935,
 -0.22536247624273123,
 -0.1006124

In [ ]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.325857  -0.999650
1 -4.296594  -0.999629
2 -3.960083  -0.999274
3 -3.510984  -0.998217
4 -3.271262  -0.997122

In [ ]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

In [ ]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [ ]:
data = np.random.randn(4, 5)
data

array([[-1.993823, -1.543212,  0.610701, -1.303781,  0.031199],
       [-0.966606, -0.011135, -1.399465, -1.212952, -0.845995],
       [ 0.9544  ,  0.624408, -0.214211,  0.996932, -0.973368],
       [-0.16014 , -1.255372,  0.839575,  0.927693, -0.470635]])

In [ ]:
result = softmax(data)
result

array([[0.038965, 0.061146, 0.526992, 0.077688, 0.295209],
       [0.16238 , 0.422172, 0.105328, 0.126925, 0.183195],
       [0.310689, 0.223364, 0.096562, 0.324189, 0.045197],
       [0.128984, 0.04314 , 0.350515, 0.382804, 0.094556]])

In [ ]:
result.sum(axis=1)

array([1., 1., 1., 1.])